cetz-package/cetz

canvas.typ
draw.typ

Also fixed rotations and flipped translating in the y direction

Fix anchor transformations for good

---

canvas.typ
util.typ
vector.typ

- Fix content bounds not being transformed
- Fix function coordinates
- Add vector lerp

Various fixes

---

cmd.typ
demo/karl-picture.typ
vector.typ

also fixes karl's picture demo which uses the pie mode

Fix `arc` PIE mode

---

canvas.typ
draw.typ
matrix.typ
util.typ

This also adds matrix multiplication and inversion

Use a single transform matrix

---

canvas.typ
draw.typ

Add documentation for some functions.

Add Function Documentation

---

src/lib/plot.typ

plot: Improve tick documentation

---

manual.typ

Unrelated to the PR: Wonderful library. Could have not wished for anything better.

docs: fix typo

---

manual.typ
src/lib/chart/boxwhisker.typ
src/lib/plot/boxwhisker.typ

Adds `plot.add-boxwhisker` and `chart.boxwhisker` to the manual.

plot: Boxwhisker manual

---

src/lib/axes.typ

Add support for customising axis label anchor in school-book style

---

src/lib/axes.typ

- Tick limit is checked before creating the (possibly huge) tick array
- Tick limit is now a configurable style value
- Fixes and improves per axis styling

axes: Make tick limit configurable

---

tests/arc/test.typ
tests/bezier-through/test.typ
tests/bounds/test.typ
tests/catmul/test.typ
tests/circle-through/test.typ
tests/circle/test.typ
tests/content/test.typ
tests/cube/test.typ
tests/grid/test.typ
tests/image/test.typ
tests/layer/test.typ
tests/local-anchor/test.typ
tests/primitives/test.typ
tests/ratio-length/test.typ
tests/relative-length/test.typ
tests/relative-no-update/test.typ
tests/ring/test.typ
tests/set-get-ctx/test.typ
tests/style/test.typ
tests/translation/test.typ

Use absolute paths for all tests.

tests: Use absolute paths

---

src/bezier.typ

Function is not used and has bugs.

bezier: Remove unused function

---

manual.typ
src/draw/grouping.typ
src/lib/tree.typ

List all available marks in the manual.

manual: List all marks

---

README.md
doc/util.typ
typst.toml

Update the repository URL to the new one.

treewide: Update repository URL

---

src/lib/plot.typ

Add some type checking assertions to `plot.plot`.

plot: Add some type checking assertions

---

src/lib/decorations/brace.typ

Fixes for the typos detected by @raphCode.

brace: Fix docs

---

README.md

Update `riemann` to `riesketcher`.

readme: Update riemann package name & URL

---

CHANGES.md
src/canvas.typ

Fixes issues with `#set place(float: true)`.

canvas: Set float to false for place calls

---

README.md

readme: Add cetz-venn

---

CHANGES.md
src/drawable.typ
src/util.typ

This is very useful for non-linear transformations (e.g. log scales in cetz-plot).

util: Allow passing a function to apply-transform

---

manual.typ

Starting to learn CeTZ and noticed a minor typo in the manual. Thanks for working on this great package!

Fixing typo in manual.typ

---

README.md

Added my packages to the "Projects using CeTZ" section

Add `chronos`, `circuiteria` and `rivet` to projects

---

src/vector.typ

Useful function to have (used in cetz-plot, should be in cetz vector lib).

vector: Add element-product function

---

CHANGES.md
README.md
docs/getting-started.mdx
docs/tutorials/karl.mdx
gallery/karls-picture.typ
gallery/paciolis.typ
gallery/periodic-table.typ
gallery/plate-capacitor.typ
gallery/tree.typ
gallery/waves.typ
typst.toml

Bump version + add changelog for a bugfix release 0.3.2 (to be released prior Typst 0.13).

treewide: Version + Changelog

---

docs/basics/coordinate-systems.mdx

doc: Fix tangent example

---

CHANGES.md
docs/advanced/custom-types.mdx
src/canvas.typ
src/draw/grouping.typ

context: Add shared-state

---

CHANGES.md
src/styles.typ

changes: Update changelog + Documentation
