draw.typ

This is done by checking if the syntax is correct in the `rotate` function then passing it off to `resolve-coordinate`.

Add function coordinate syntax to `rotate` function

---

canvas.typ
draw.typ

This PR adds the option of having padding around content() blocks, as per https://github.com/johannes-wolf/typst-canvas/issues/53#issue-1731344063.
Set via `content-padding(length)` or `content(..., padding: length)`.

Add padding around content blocks

---

canvas.typ

Fixes #116 
With the code
```
#let drawing1 = cetz.canvas(debug: false, background: red, {
import cetz.draw: *
circle(())
circle((1,1))
})
#let drawing2 = cetz.canvas(debug: false, background: blue, {
import cetz.draw: *
circle(())
circle((2,2))
})
#stack(dir:ltr, align(horizon, drawing1), drawing2)
```
Before:
After:

Fix alignment

---

scripts/package

Fixes #203
- Use /usr/bin instead of /bin
- Use perl instead of awk/gawk/nawk
- Put `-r` to the front of `cp`'s arguments 
- Use ugly tricks because macOS does not ship realpath
Perl should come with Windows bash/git bash installation, so this should work on Windows, too.
The changes can be tested via `just install`

script: Fix issues with macOS

---

src/aabb.typ
src/canvas.typ

Simplify AABB calculation and move it to its own file.
Also support 3 dim vectors (for later use in some draw commands).

aabb: Move bounding box calculation into aabb.typ

---

manual.typ
src/lib/decorations.typ

This PR adds a new style key called `outer-pointiness` for the braces from the `decorations` library. It effectively controls the same thing as the existing `pointiness` but for the outer points instead. This adds the two new debug points `i` and `j` (what was `i` before is now `k`). Setting this to `0` (as is the default) provides the same behaviour as before.
I also moved documentation of the style keys from the function's doc-comment to the `manual.typ` file just like the other elements do it.
Screenshot of the updated example:
I am also second guessing my choice from yesterday in #227 that a pointiness of 0 is the maximum. Intuitively I would expect 1 to be the max, but then again with the angles it makes sense to have `0deg` as the max :shrug:. If you think we should change this I …

Improvements to `brace`

---

manual.typ
src/draw/shapes.typ
src/lib.typ

Fixes the compilation of manual.typ.

doc: Fix manual

---

src/lib/chart.typ
src/lib/chart/dendrogram.typ
tests/chart/dendrogram/test.typ

Dendrogram chart for displaying linkages of binary clusters. Currently supports individual styling of leaves. Would be commonly used in clustering analyses. Input format matches that of matlab.
```typst
#set page(width: auto, height: auto)
#import "../../../src/lib.typ": *
#let dendrogram-data = (
(1, 2, 0.5000),
(3, 4, 1.0000),
(6, 7, 2.0616),
(5, 8, 2.5000)
)
#canvas({
chart.dendrogram(
size: (10, 10),
x-ticks: (
(1,[S1]),
(2,[S2]),
(3,[B1]),
(4,[B2]),
(5,[Control])
),
dendrogram-style: (idx)=>{
if idx in (0,){ return (stroke: red + 1pt)}
if idx in (1,){ return (stroke: green + 1pt)}
//if idx in (2,){ return (stroke: blue + 1pt)}
},
dendrogram-data)
})
```

Introducing the dendrogram

---

src/lib/plot/contour.typ

Spotted this just now, cleaned up the code to work with binary rather than decimal

Save you some headache on `get-case`

---

justfile
scripts/test

This allows to run tests by name (regexp):
just test plot
just test plot anchor
All filter strings are concatted to one regexp by "|" and passed to grep.

tests: Support test filters

---

src/matrix.typ
src/util.typ

This change gives about -100 ms for a line plot with 1000 data points.
Since matrix-vector multiplication is done a lot, this specialization should be used. 
We actually never user non 4x4 matrices, so we could think about not supporting other matrix sizes in general.

matrix: Unroll matrix-vector product

---

scripts/test

`--max-args` (`-n`) is mutually exclusive with `-I` (since `-I` implies a single argument); using both causes a warning.
This just gets rid of that warning.
I'm looking to win the "most inconsequential pull request of all time" competition with this one 😛

Remove -n 1 argument from xargs in test script

---

src/anchor.typ
src/coordinate.typ
src/deps.typ
src/draw/grouping.typ
src/lib.typ
src/util.typ

Groups dependencies to external libs in a single file to prevent accidentally importing multiple versions.
Fixes #403

Group external dependencies in single file

---

justfile
scripts/package
scripts/relpaths

This allows installing cetz with all paths in all *.typ files changed to relative ones.
@Andrew15-5: Please test this via `just package <your-directory> --relative-paths`.
As soon as Typst supports changing the package path, this cursed script must get removed.

scripts: Add script for changing all abs paths

---

src/canvas.typ

Fixes #345.
For some reason, `line` measures 0pt in width (with `length: 1cm`). This only happens insides `tablex`. Using `box` works.

canvas: Fix bug when using canvas insides tablex

---

src/draw/transformations.typ

Alignment terms aren't used with "-" in normal text, only in programs like Typst. And the overall use of alignment terms was inconsistent.

Made documentations 2D alignment consistent

---

src/lib/axes.typ

Using canvas relative lengths is useless, as everything scales up if one uses a length different from 1 cm.
- Adds the option to specify school-book axis origin offset #419
- Adds style keys for configuring automatic tick calculation: #399

plot: Use absolute lengths in default style

---

src/lib/tree.typ

This solves the issue I created last week (#429) and adds another layout choice where the parent is offset relative to the children.
Both values seem more useful for "right" and "left" direction, and actually, the "after-end" option seems more useful to me, as it allows to render a more hierarchical layout without overlapping, like this question asked on Discord: https://discord.com/channels/1054443721975922748/1193008120688037988
I did not change the existing behavior, but it was very surprising to me to see that when choosing "right" or "left" as direction, the nodes at filled from bottom to top, and it is necessary to choose "end" to have the parent on top. Is it that way for a reason? I would prefer a "before-beginning" rather than "after-end" to indicate that I want my parent above …

In tree, add "end" and "after-end" as values for parent-position

---

README.md

A shameless plug for my CeTZ-based diagramming package https://github.com/Jollywatt/typst-fletcher which is nearing maturity.

Add `fletcher` to Projects using CeTZ

---

src/lib.typ

Intersection functions should be accessible via `cetz.intersection.*` (requested by the fletcher author).

lib: Export intersection functions

---

CHANGES.md
src/lib/plot/annotation.typ

Annotation bounds calculation must happen without a transformation, as the coordinates are in plot coordinates.

plot: Fix annotations

---

src/path-util.typ

I found this bug by attempting to use a path anchor on a group with a vertical line:
```typc
group(name: "g", {
line((0,0), (0,1))
})
circle("g.start")
```
The group's width becomes zero so some of the points on its bounds are equal. This causes their length to be zero, which causes a divide zero error in `path-util._point-on-line-segment`.
I have fixed this by checking if length is a zero integer and setting it to 1 if so. I'm not sure what other issues this may cause...

Fix: Prevent divide by zero error if a segment has zero length

---

manual.typ

doc: Add default value of `shorten-to` to the docs

---

src/draw/transformations.typ

Fixes one inconsistency since #409.
Used `\rg -i '(bottom|top|left|right)[- ](bottom|top|left|right)'` again.

Make 2D alignment great again

---

LICENSE
typst.toml

So consumers do not have to be GPL licensed.
Licencing under LGPL does not allow using GPL-code though, so the kontourclip PR #535 can't be merged!

licence: LGPLv3 is what we want

---

src/drawable.typ

I see this file had a double import, I don't see why it is necessary

double import path-util necessary?

---

CHANGES.md
src/canvas.typ
src/process.typ

- Process: Check that element names do not contain '.'
- Canvas: We use `kind` everywhere else as it does not shadow Typst's `type` function + unpacking the array

Validate Element Names

---

src/draw/shapes.typ

It took me a while to figure out why the text in the `content` example
```typst
line((0, 0), (3, 1), name: "line")
content(
("line.start", 0.5, "line.end"),
angle: "line.end",
padding: .1,
anchor: "south",
[Text on a line]
)
```
was not centered above the line. I suppose centering is a very common use case (maybe even intended in the example?), so I'd suggest using `50%` here to save folks some time figuring out that 0.5 is not a percentage but an absolute length :slightly_smiling_face:

doc: Center text on line in content shape example

---

src/draw/grouping.typ
src/lib.typ
src/lib/plot-stub.typ

I think panicking with a message that cetz-plot has been moved to its own repo is helpful.

Panic on plot.plot

---

src/lib.typ
src/lib/plot-stub.typ

It can result in overriding cetz-plots `plot` function, if imported after `cetz-plot`.

lib: Remove plot stub

---

docs/basics/marks.mdx

Add missing documentation for the mark `anchor` attribute.

docs: Add mark `anchor` documentation

---

.gitmodules

Hi, I am currently trying to upstream my Typst package support for Nixpkgs, and wrapping cetz into Nixpkgs is part of that PR. However, I failed to bump cetz from v0.2.2 to v0.3.1 because the latter uses a read-write URL for its submodule, namely `common`. This blocks nix source fetcher to clone the source from its submodule, as it requires the access capability.
This RP addresses this issue by replacing the submodule URL with read-only URL, which should be useful in general for automatic package builders.

Replace the URL in the submodule with read-only URL

---

src/coordinate.typ
src/deps.typ
src/path-util.typ

Tested with current `master`, cetz does not compile anymore because of some leftover `type`<=>`string` checks.

treewide: Prepare for upcomming typst version

---

src/draw/shapes.typ

Add a default anchor for closed lines. This allows using intersection syntax (`line`) with
polygons drawn using `line()`.
Fixes #776.

line: Add default anchor for closed lines

---

docs/basics/coordinate-systems.mdx

The syntax explanation is mixed up. You can confirm that your self by comparing it to the given example right below the change.

fix typo coordinate-systems.mdx

---

src/canvas.typ
src/coordinate.typ
src/matrix.typ
src/vector.typ
tests/transform-precission/test.typ

Gives ~2 seconds when running tests.

perf: Some performance improvements

---

src/aabb.typ

While searching for performance improvements, I tried to rewrite `aabb`. I have not managed to make a dent in the running time, but this PR suggest a small change to make the code slightly more readable. Now the init logic is moved outside the loop, which allows the `enumerate` to be removed. Also, it makes the logic more clear. It's now clearer that there might be a bug, because the `init == none and pts.len() == 0` case seems to not be handled (in the old and new code, it would just default to `init`, but that was `none` so the `bounds.low` line will then crash.)
Since the diff is so confusing, this was the code before this change:
```typ
#let aabb(pts, init: none) = {
let bounds = init
if type(pts) == array {
for (i, pt) in pts.enumerate() {
if bounds == none and i == 0 {
bounds = …
```

Small `aabb` rewrite

---

.gitignore
src/draw/shapes.typ

This PR suggests to add a fast path for rectangles without a radius. When benchmarking with 100 and 500 points, it is about 5% faster on my system. My test document was
```typ
#import "/src/lib.typ": *
#set page(width: auto, height: auto)
#let pts = array.range(500).map(x => (x, x))
#canvas({
import draw: *
for pt in pts {
rect(pt, (rel: (0.5, 0.5), to: pt), fill: blue, stroke: none)
}
})
```
and my benchmark command was
```sh
$ hyperfine --warmup=1 --runs=10 "typst c --ppi=10 --format=png tmp.typ"
```
which generates a 106 KB 1986 x 1986 image.

Add fast path for rect without radius

---

src/bezier.typ

It's quite a silly change, but I'm getting consistently 3%-4% better performance with
```typst
#import "/src/lib.typ": *
#set page(width: auto, height: auto)
#let pts = array.range(500).map(x => (x, x))
#canvas({
import draw: *
for pt in pts {
circle(pt, fill: blue, stroke: none)
}
})
```
and
```sh
$ hyperfine --warmup=1 --runs=10 "typst c --ppi=10 --format=png tmp.typ"
```
Are you in favor of rewrites like this? Or should I see whether this can be fixed in the Typst compiler? 
I personally would lean in favor of biting the bullet and rewriting these kinds of code because it sort of makes sense that defining a function at the module level once is faster than constantly defining a function as an inner function. Also, readability-wise having the function on the top level is easier to read …

Extract `dim-extrema` from `cubic-extrema`

---

README.md

Remove unmaintained projects or projects using old versions of cetz from the list of “Projects Using CeTZ”

readme: Remove unmaintained projects

---

README.md

Hi CeTZ maintainers 👋,
I'm happy to introduce you to Zap, a package to draw electronic circuits, currently available on Typst Universe (`v0.2.0`).
I think, as Zap uses a lot of CeTZ in the background, that it would be nice to add it on the CeTZ `README.md`.
Here's a suggestion, of course you are free to change the description.
Have a nice day ☀️!

Add Zap mention

---

docs/basics/styling.mdx

The `path` function is replaced by `curve`.
https://typst.app/docs/changelog/0.13.0/#visualization

Update a deprecated link to typst.app/docs

---

src/styles.typ

This is a simple implementation for #913 adding support for an `array` value for the `root` of `styles.resolve`, allowing nested style resolving

styles: Support multi-level style root

---

src/draw/shapes.typ

The `@@` was quite striking; it was the only occurrence in the codebase.
Note that I did not yet set up a full-fledged environment (and I don't immediately see where and how the docs are built), so this fix is _untested_.
While looking at links throughout the docs, I also noticed that CeTZ functions are often unstyled, but sometimes `monospace`. Should I open another PR to move it all to monospace?

docs: fix link from merge-path to hide
